# Generated by Django 4.2 on 2023-04-27 03:59

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='brands',
            fields=[
                ('bid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('bname', models.CharField(default='', max_length=50, null=True)),
                ('bdescription', models.TextField(default='', max_length='100')),
                ('bdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('brmdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('removestate', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='categorys',
            fields=[
                ('cid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('catname', models.CharField(default='', max_length=50, null=True)),
                ('catdescription', models.TextField(default='', max_length='100')),
                ('catimage', models.ImageField(default='noimage.jpg', upload_to='Categorys')),
                ('catdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('catrmdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('removestate', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('oid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('proqty', models.IntegerField(default=1)),
                ('productstatus', models.CharField(default='conform', max_length=50)),
                ('paymentmode', models.CharField(default='', max_length=50)),
                ('returnpro', models.CharField(default='No', max_length=50)),
                ('ordate', models.DateTimeField(default=django.utils.timezone.now)),
                ('canceldate', models.DateTimeField(default=django.utils.timezone.now)),
                ('deliveddate', models.DateField(default=django.utils.timezone.now)),
                ('returndate', models.DateField(default=django.utils.timezone.now)),
                ('removestate', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('proid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('proname', models.CharField(default='', max_length=500)),
                ('prodescription', ckeditor.fields.RichTextField()),
                ('proprice', models.IntegerField(default=0)),
                ('propercentage', models.IntegerField(default=0)),
                ('prostock', models.IntegerField(default=0)),
                ('procolorname', models.CharField(default='', max_length=50)),
                ('procolor', models.CharField(default='', max_length=50)),
                ('ram', models.CharField(default='No', max_length=50)),
                ('rom', models.CharField(default='No', max_length=50)),
                ('clothes_gender', models.CharField(default='No', max_length=50)),
                ('clothes_size', models.CharField(default='No', max_length=50)),
                ('watch_type', models.CharField(default='No', max_length=50)),
                ('proimage1', models.ImageField(default='noimage.png', upload_to='ProductsImages')),
                ('proimage2', models.ImageField(default='noimage.png', upload_to='ProductsImages')),
                ('proimage3', models.ImageField(default='noimage.png', upload_to='ProductsImages')),
                ('proimage4', models.ImageField(default='noimage.png', upload_to='ProductsImages')),
                ('proimage5', models.ImageField(default='noimage.png', upload_to='ProductsImages')),
                ('prodate', models.DateTimeField(default=django.utils.timezone.now)),
                ('prormdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('removestate', models.IntegerField(default=0)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webadminsiteapp.brands')),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webadminsiteapp.categorys')),
            ],
        ),
        migrations.CreateModel(
            name='uwishlist',
            fields=[
                ('wid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('wdate', models.DateField(default=django.utils.timezone.now)),
                ('proid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webadminsiteapp.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=50)),
                ('lastname', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=10)),
                ('dob', models.CharField(default='', max_length=20)),
                ('gender', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('country', models.CharField(default='', max_length=50)),
                ('profileimage', models.ImageField(default='blank-profile-picture.png', upload_to='UsersProfile')),
                ('twostep', models.IntegerField(default=0)),
                ('uotp', models.CharField(default='', max_length=6)),
                ('rmuserdate', models.DateField(default=django.utils.timezone.now)),
                ('reaccountdate', models.DateField(default=django.utils.timezone.now)),
                ('removestate', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.CharField(default='', max_length=50)),
                ('latitude', models.CharField(default='', max_length=50)),
                ('login_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('userid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='useraddress',
            fields=[
                ('addid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('addtitle', models.CharField(default='address', max_length=100)),
                ('adddescription', models.TextField(default='')),
                ('removestate', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='returnproduct',
            fields=[
                ('reid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('rnproce', models.CharField(default='', max_length=20)),
                ('rnresone', models.CharField(default='', max_length=500)),
                ('rncomment', models.TextField(default='')),
                ('rndate', models.DateField(default=django.utils.timezone.now)),
                ('rncanceldate', models.DateField(default=django.utils.timezone.now)),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webadminsiteapp.orders')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='products_other_details',
            fields=[
                ('otherid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('other_details', ckeditor.fields.RichTextField(default='')),
                ('show_other', models.CharField(default='hide', max_length=50)),
                ('removestate', models.IntegerField(default=0)),
                ('proid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webadminsiteapp.products')),
            ],
        ),
        migrations.CreateModel(
            name='products_osprocesser_details',
            fields=[
                ('osproid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('osprocesser_details', ckeditor.fields.RichTextField(default='')),
                ('show_osprocesser', models.CharField(default='hide', max_length=50)),
                ('removestate', models.IntegerField(default=0)),
                ('proid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webadminsiteapp.products')),
            ],
        ),
        migrations.CreateModel(
            name='products_general_details',
            fields=[
                ('geneid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('general_details', ckeditor.fields.RichTextField(default='')),
                ('removestate', models.IntegerField(default=0)),
                ('proid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webadminsiteapp.products')),
            ],
        ),
        migrations.CreateModel(
            name='products_displays_details',
            fields=[
                ('disid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('display_details', ckeditor.fields.RichTextField(default='')),
                ('show_display', models.CharField(default='hide', max_length=50)),
                ('removestate', models.IntegerField(default=0)),
                ('proid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webadminsiteapp.products')),
            ],
        ),
        migrations.CreateModel(
            name='products_dimensions_warranty_details',
            fields=[
                ('dimenid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('dimension_warranty_details', ckeditor.fields.RichTextField(default='')),
                ('show_dimwarr', models.CharField(default='hide', max_length=50)),
                ('removestate', models.IntegerField(default=0)),
                ('proid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webadminsiteapp.products')),
            ],
        ),
        migrations.CreateModel(
            name='products_connectivity_details',
            fields=[
                ('connid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('connectivity_details', ckeditor.fields.RichTextField(default='')),
                ('show_connectivity', models.CharField(default='hide', max_length=50)),
                ('removestate', models.IntegerField(default=0)),
                ('proid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webadminsiteapp.products')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='deliaddr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webadminsiteapp.useraddress'),
        ),
        migrations.AddField(
            model_name='orders',
            name='proid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webadminsiteapp.products'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efirstname', models.CharField(default='', max_length=50)),
                ('elastname', models.CharField(default='', max_length=50)),
                ('ephone', models.CharField(default='', max_length=10)),
                ('edob', models.CharField(default='', max_length=20)),
                ('egender', models.CharField(max_length=50)),
                ('eaddress', models.TextField(default='')),
                ('edeparements', models.CharField(default='', max_length=50)),
                ('salary', models.IntegerField(default=3000)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('country', models.CharField(default='', max_length=50)),
                ('profileimage', models.ImageField(default='blank-profile-picture.png', upload_to='EmployeeProfile')),
                ('ehiredate', models.DateField(default=django.utils.timezone.now)),
                ('etwostepauthonetication', models.IntegerField(default=0)),
                ('eOTP', models.CharField(default='', max_length=6)),
                ('rmempdate', models.DateField(default=django.utils.timezone.now)),
                ('removestate', models.IntegerField(default=0)),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='customerissues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuesid', models.UUIDField(default=uuid.uuid4)),
                ('issueshort', models.CharField(default='', max_length=100)),
                ('issues', models.TextField(default='')),
                ('idate', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('cartid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('proqty', models.IntegerField(default=0)),
                ('catproprice', models.IntegerField(default=0)),
                ('wdate', models.DateField(default=django.utils.timezone.now)),
                ('deliaddr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webadminsiteapp.useraddress')),
                ('proid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webadminsiteapp.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='brands',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webadminsiteapp.categorys'),
        ),
        migrations.CreateModel(
            name='banners',
            fields=[
                ('bannerid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('bannerImage', models.ImageField(default='noimage.jpg', upload_to='Banners')),
                ('uploadedate', models.DateTimeField(default=django.utils.timezone.now)),
                ('removestate', models.IntegerField(default=0)),
                ('proid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webadminsiteapp.products')),
            ],
        ),
    ]
